export const DARKMODE = "DARKMODE";
export const GETPALETTES = "GETPALETTES";
export const GETSAVEDPALETTES = "GETSAVEDPALETTES";
export const DELETEPALETTE = "DELETEPALETTE";
export const SAVEPALETTE = "SAVEPALETTE";
export const CREATEPALETTE = "CREATEPALETTE";
